apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  labels:
    k0rdent.mirantis.com/managed: 'true'
  name: catalog-templates
  namespace: kcm-system
spec:
  interval: 10m0s
  provider: generic
  type: oci
  url: oci://ghcr.io/k0rdent/catalog/charts/